import type{ReactNode}from"react";import{AlertCircle,CheckCircle2,Clock3,Info,LoaderCircle,XCircle}from"lucide-react";
export function Button({children,variant="primary",...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"secondary"|"danger"|"quiet"}){return <button className={`button ${variant}`} {...props}>{children}</button>}
export function Field({label,hint,error,...props}:React.InputHTMLAttributes<HTMLInputElement>&{label:string;hint?:string;error?:string}){return <label className="field"><span>{label}</span><input {...props}/>{hint&&<small>{hint}</small>}{error&&<small className="error">{error}</small>}</label>}
export function SelectField({label,children,...props}:React.SelectHTMLAttributes<HTMLSelectElement>&{label:string;children:ReactNode}){return <label className="field"><span>{label}</span><select {...props}>{children}</select></label>}
export function Modal({title,children,onClose}: {title:string;children:ReactNode;onClose:()=>void}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><header><h2 id="modal-title">{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close"><XCircle/></button></header>{children}</section></div>}
export function Status({kind,label}:{kind:"green"|"amber"|"red"|"grey";label:string}){const Icon=kind==="green"?CheckCircle2:kind==="amber"?Clock3:kind==="red"?AlertCircle:Info;return <span className={`status ${kind}`}><Icon/> {label}</span>}
export function Empty({icon,heading,body,action}:{icon?:ReactNode;heading:string;body:string;action?:ReactNode}){return <div className="empty">{icon}<h3>{heading}</h3><p>{body}</p>{action}</div>}
export function Loading(){return <div className="loading"><LoaderCircle className="spin"/> Loading securely…</div>}
export function ErrorState({message,retry}:{message:string;retry?:()=>void}){return <div className="error-state"><AlertCircle/><div><strong>Couldn’t load this information</strong><p>{message}</p>{retry&&<Button variant="secondary" onClick={retry}>Try again</Button>}</div></div>}
export const fmtDate=(value?:string)=>value?new Intl.DateTimeFormat("en-NG",{day:"numeric",month:"short",year:"numeric"}).format(new Date(value)):"Date not provided";
