import { config } from "./config.js";

export type FacilityCategory="hospital"|"laboratory"|"diagnostic_centre"|"clinic";
export type Facility={provider:"google";providerPlaceId:string;name:string;category:FacilityCategory;address?:string;latitude:number;longitude:number;distanceMetres:number;rating?:number;reviewCount?:number;openNow?:boolean;phone?:string;website?:string;hours?:string[]};
const fields="places.id,places.displayName,places.primaryType,places.types,places.formattedAddress,places.location,places.rating,places.userRatingCount,places.currentOpeningHours,places.nationalPhoneNumber,places.websiteUri";
const typeMap:Record<string,FacilityCategory>={hospital:"hospital",medical_clinic:"clinic",clinic:"clinic",medical_laboratory:"laboratory",diagnostic_lab:"laboratory",diagnostic_center:"diagnostic_centre"};
export const distance=(aLat:number,aLng:number,bLat:number,bLng:number)=>{const r=6371000,dLat=(bLat-aLat)*Math.PI/180,dLng=(bLng-aLng)*Math.PI/180;const a=Math.sin(dLat/2)**2+Math.cos(aLat*Math.PI/180)*Math.cos(bLat*Math.PI/180)*Math.sin(dLng/2)**2;return 2*r*Math.asin(Math.sqrt(a))};
function category(place:any):FacilityCategory{for(const t of [place.primaryType,...(place.types??[])])if(typeMap[t])return typeMap[t];return"clinic"}
function normalise(place:any,lat:number,lng:number):Facility{return{provider:"google",providerPlaceId:place.id,name:place.displayName?.text??"Unnamed facility",category:category(place),address:place.formattedAddress,latitude:place.location.latitude,longitude:place.location.longitude,distanceMetres:Math.round(distance(lat,lng,place.location.latitude,place.location.longitude)),rating:place.rating,reviewCount:place.userRatingCount,openNow:place.currentOpeningHours?.openNow,phone:place.nationalPhoneNumber,website:place.websiteUri,hours:place.currentOpeningHours?.weekdayDescriptions}}
function key(){if(!config.GOOGLE_PLACES_API_KEY)throw Object.assign(new Error("Find Care provider is not configured."),{statusCode:503,code:"PROVIDER_NOT_CONFIGURED"});return config.GOOGLE_PLACES_API_KEY}
const types:Record<string,string[]>={all:["hospital","medical_clinic","medical_laboratory"],hospital:["hospital"],laboratory:["medical_laboratory"],diagnostic_centre:["medical_laboratory"],clinic:["medical_clinic"]};
export async function nearby(lat:number,lng:number,kind:string,radius:number){const response=await fetch("https://places.googleapis.com/v1/places:searchNearby",{method:"POST",headers:{"content-type":"application/json","X-Goog-Api-Key":key(),"X-Goog-FieldMask":fields},body:JSON.stringify({includedTypes:types[kind]??types.all,maxResultCount:20,rankPreference:"DISTANCE",locationRestriction:{circle:{center:{latitude:lat,longitude:lng},radius}}}),signal:AbortSignal.timeout(10000)});if(!response.ok)throw Object.assign(new Error("Facility search is temporarily unavailable."),{statusCode:response.status===429?429:502,code:response.status===429?"PROVIDER_QUOTA":"PROVIDER_ERROR"});const data:any=await response.json();return(data.places??[]).map((p:any)=>normalise(p,lat,lng)).sort((a:Facility,b:Facility)=>a.distanceMetres-b.distanceMetres)}
export async function geocode(query:string){const url=`https://maps.googleapis.com/maps/api/geocode/json?address=${encodeURIComponent(query)}&region=ng&key=${encodeURIComponent(key())}`;const response=await fetch(url,{signal:AbortSignal.timeout(10000)});if(!response.ok)throw Object.assign(new Error("Location search is temporarily unavailable."),{statusCode:502,code:"PROVIDER_ERROR"});const data:any=await response.json();if(data.status==="REQUEST_DENIED")throw Object.assign(new Error("Google rejected the server key. Enable Geocoding API and check its API restrictions."),{statusCode:503,code:"PROVIDER_KEY_REJECTED"});if(data.status==="OVER_QUERY_LIMIT")throw Object.assign(new Error("The Google Maps quota is currently unavailable."),{statusCode:429,code:"PROVIDER_QUOTA"});if(data.status!=="OK"||!data.results?.[0])throw Object.assign(new Error("We could not find that location."),{statusCode:422,code:"LOCATION_NOT_FOUND"});const result=data.results[0];return{latitude:result.geometry.location.lat,longitude:result.geometry.location.lng,label:result.formatted_address}}
export async function details(placeId:string,origin?:{lat:number;lng:number}){const response=await fetch(`https://places.googleapis.com/v1/places/${encodeURIComponent(placeId)}`,{headers:{"X-Goog-Api-Key":key(),"X-Goog-FieldMask":fields.replaceAll("places.","")},signal:AbortSignal.timeout(10000)});if(!response.ok)throw Object.assign(new Error("Facility details are unavailable."),{statusCode:response.status===404?404:502,code:"PROVIDER_ERROR"});const p:any=await response.json();return normalise(p,origin?.lat??p.location.latitude,origin?.lng??p.location.longitude)}
