import bcrypt from "bcryptjs"; import { db, ensureIndexes, closeDb } from "./db.js";
const d=await db(); await ensureIndexes();
await Promise.all(["users","patients","records","record_versions","history","observations","grants","audit_events","notifications","facilities"].map(name=>d.collection(name).deleteMany({seed:true})));
const patientId=(await d.collection("patients").insertOne({seed:true,healthId:"NTH-DEMO-8F3K2A",fullName:"Amara Okafor",dateOfBirth:"1992-04-16",bloodGroup:"O+",bloodGroupSource:"self_reported",genotype:"AA",genotypeSource:"self_reported",city:"Abuja",state:"FCT",version:1,createdAt:new Date(),updatedAt:new Date()})).insertedId;
const secondPatientId=(await d.collection("patients").insertOne({seed:true,healthId:"NTH-DEMO-7B9M4Q",fullName:"Tunde Bello",version:1,createdAt:new Date(),updatedAt:new Date()})).insertedId;
const passwordHash=await bcrypt.hash("DemoPatient!2026",12); const patientUser=(await d.collection("users").insertOne({seed:true,email:"patient@netrue.test",passwordHash,fullName:"Amara Okafor",roles:["patient"],patientId,state:"active",emailVerified:true,createdAt:new Date()})).insertedId;
await d.collection("users").insertOne({seed:true,email:"second@netrue.test",passwordHash,fullName:"Tunde Bello",roles:["patient"],patientId:secondPatientId,state:"active",emailVerified:true,createdAt:new Date()});
await d.collection("users").insertOne({seed:true,email:"doctor@netrue.test",passwordHash,fullName:"Dr. Chinedu Eze",roles:["practitioner"],practitionerStatus:"verified",credentialExpiresAt:new Date("2027-12-31"),state:"active",emailVerified:true,createdAt:new Date()});
const records=[{title:"Complete blood count",category:"laboratory",reportDate:"2026-09-28",sourceType:"patient_upload"},{title:"Abdominal ultrasound",category:"imaging",reportDate:"2026-07-11",sourceType:"facility_submitted"},{title:"Annual clinic visit",category:"visit",reportDate:"2026-03-04",sourceType:"manual_entry"}];
for(const item of records){const id=(await d.collection("records").insertOne({seed:true,...item,patientId,status:"available",version:1,createdAt:new Date(),updatedAt:new Date()})).insertedId;await d.collection("record_versions").insertOne({seed:true,recordId:id,patientId,version:1,snapshot:item,finalisedAt:new Date()});if(item.category==="laboratory")await d.collection("observations").insertOne({seed:true,recordId:id,patientId,label:"Haemoglobin",rawValue:"14.1",numericValue:14.1,unit:"g/dL",lower:13,upper:17,rawInterval:"13–17 g/dL",laboratoryFlag:"normal",confirmed:true,evaluation:{status:"grey",reason:"feature_disabled",wording:"Automated comparison is not enabled. View the original report or ask the laboratory.",ruleVersion:"1.0"},createdAt:new Date()});}
await d.collection("history").insertMany([{seed:true,patientId,type:"allergies",label:"Penicillin",details:"Rash reported in childhood",state:"reported",source:"self_reported",createdAt:new Date(),updatedAt:new Date()},{seed:true,patientId,type:"medications",label:"Amlodipine 5 mg",details:"Once daily",state:"confirmed",source:"clinician_confirmed",createdAt:new Date(),updatedAt:new Date()},{seed:true,patientId,type:"conditions",label:"Hypertension",state:"confirmed",source:"facility_submitted",createdAt:new Date(),updatedAt:new Date()}]);
await d.collection("notifications").insertOne({seed:true,userId:patientUser,title:"Record ready",message:"A report finished processing and is ready to view.",read:false,createdAt:new Date()});
await d.collection("facilities").insertMany([{seed:true,name:"Fictional Cedar Medical Centre",type:"Hospital",state:"FCT",city:"Abuja",address:"12 Demo Avenue, Wuse",phone:"+234 000 000 0000",services:["General practice","Laboratory"],hours:"Mon–Sat, 8:00–18:00",verificationStatus:"development_fixture",source:"Synthetic development data",lastCheckedAt:new Date(),status:"active"},{seed:true,name:"Fictional Lagoon Diagnostics",type:"Laboratory",state:"Lagos",city:"Ikeja",address:"4 Sample Road, Ikeja",phone:"+234 000 000 0001",services:["Laboratory","Imaging"],hours:"Mon–Fri, 7:00–17:00",verificationStatus:"development_fixture",source:"Synthetic development data",lastCheckedAt:new Date(),status:"active"}]);
console.log("Synthetic demo seeded. Patient: patient@netrue.test / DemoPatient!2026 | Practitioner: doctor@netrue.test / DemoPatient!2026 / MFA 123456"); await closeDb();
