import Fastify from "fastify"; import cookie from "@fastify/cookie"; import cors from "@fastify/cors"; import helmet from "@fastify/helmet"; import multipart from "@fastify/multipart"; import rateLimit from "@fastify/rate-limit"; import staticPlugin from "@fastify/static"; import { existsSync } from "node:fs"; import { dirname, resolve } from "node:path"; import { fileURLToPath } from "node:url";
import { config } from "./config.js"; import { db, ensureIndexes, closeDb } from "./db.js"; import { routes } from "./routes.js";
import { startReminderWorker, stopReminderWorker } from "./reminders.js";
const app=Fastify({logger:{redact:["req.headers.cookie","req.headers.authorization","body.password","body.mfaCode"]},requestIdHeader:"x-request-id"});
await app.register(cookie); await app.register(cors,{origin:config.APP_ORIGIN,credentials:true,methods:["GET","POST","PATCH","DELETE","OPTIONS"]}); await app.register(helmet,{contentSecurityPolicy:{directives:{defaultSrc:["'self'"],imgSrc:["'self'","data:"],styleSrc:["'self'","'unsafe-inline'"],scriptSrc:["'self'"],connectSrc:["'self'",config.API_ORIGIN]}}}); await app.register(rateLimit,{max:120,timeWindow:"1 minute"}); await app.register(multipart,{limits:{fileSize:10*1024*1024,files:5}});
app.get("/health/live",async()=>({status:"ok"})); app.get("/health/ready",async(req,rep)=>{try{await (await db()).command({ping:1});return {status:"ready",database:"ok",scanner:config.SCANNER_MODE==="fail-closed"?"unavailable_fail_closed":config.SCANNER_MODE,objects:existsSync(config.UPLOAD_DIR)?"ok":"initialising"}}catch{return rep.code(503).send({status:"not_ready",database:"unavailable",scanner:"unknown",objects:"unknown"})}});
await routes(app); const webRoot=resolve(dirname(fileURLToPath(import.meta.url)),"../../web/dist"); if(!existsSync(webRoot))throw new Error(`Web production build not found at ${webRoot}`);await app.register(staticPlugin,{root:webRoot,wildcard:false});app.setNotFoundHandler((req,rep)=>{if(req.url.startsWith("/v1/")||req.url.startsWith("/health/"))return rep.code(404).send({code:"NOT_FOUND",message:"Route not found.",requestId:req.id});return rep.type("text/html").sendFile("index.html")});
app.setErrorHandler((error,req,rep)=>{req.log.error({err:error},"request failed");if((error as any).code==="FST_REQ_FILE_TOO_LARGE")return rep.code(413).send({code:"FILE_TOO_LARGE",message:"Files must be 10 MB or smaller.",requestId:req.id});return rep.code((error as any).statusCode??500).send({code:"REQUEST_FAILED",message:(error as any).statusCode&&((error as any).statusCode<500)?error.message:"The request could not be completed.",requestId:req.id})});
await ensureIndexes();startReminderWorker(); const shutdown=async()=>{stopReminderWorker();await app.close();await closeDb();};process.on("SIGTERM",shutdown);process.on("SIGINT",shutdown);await app.listen({port:config.PORT,host:"0.0.0.0"});
