import { useMemo, useRef, useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Building2, Clock3, ExternalLink, FlaskConical, Heart, List, LocateFixed, Map, MapPin, Navigation, Phone, Search, Star, X } from "lucide-react";
import { api, send } from "../api";
import { Button, Empty, Loading, Status } from "../components";

type Facility={provider:"google";providerPlaceId:string;name:string;category:string;address?:string;latitude:number;longitude:number;distanceMetres:number;rating?:number;reviewCount?:number;openNow?:boolean;phone?:string;website?:string;hours?:string[]};
const types=[{id:"all",label:"All",icon:Building2},{id:"hospital",label:"Hospitals",icon:Building2},{id:"laboratory",label:"Labs",icon:FlaskConical},{id:"diagnostic_centre",label:"Diagnostics",icon:FlaskConical},{id:"clinic",label:"Clinics",icon:Building2}];
const distanceLabel=(metres:number)=>metres<1000?`${Math.max(1,Math.round(metres))} m`:`${(metres/1000).toFixed(metres<10000?1:0)} km`;
const directions=(f:Facility)=>`https://www.google.com/maps/dir/?api=1&destination=${f.latitude},${f.longitude}&destination_place_id=${encodeURIComponent(f.providerPlaceId)}`;

export default function Facilities(){
  const qc=useQueryClient(),input=useRef<HTMLInputElement>(null);const[type,setType]=useState("all"),[sort,setSort]=useState("nearest"),[view,setView]=useState<"list"|"map">("list"),[query,setQuery]=useState(""),[searchUrl,setSearchUrl]=useState(""),[message,setMessage]=useState(""),[radius,setRadius]=useState(5000),[selected,setSelected]=useState<Facility|null>(null);
  const results=useQuery({queryKey:["care",searchUrl],queryFn:()=>api<any>(searchUrl),enabled:!!searchUrl,retry:false});
  const favourites=useQuery({queryKey:["favourites"],queryFn:()=>api<any>("/v1/favourites")});
  const saved=new Set((favourites.data?.items??[]).map((x:any)=>x.providerPlaceId));
  const save=useMutation({mutationFn:(f:Facility)=>send("POST","/v1/favourites",f),onSuccess:()=>qc.invalidateQueries({queryKey:["favourites"]})});
  const remove=useMutation({mutationFn:(id:string)=>send("DELETE",`/v1/favourites/provider/${encodeURIComponent(id)}`),onSuccess:()=>qc.invalidateQueries({queryKey:["favourites"]})});
  const items=useMemo(()=>{const copy=[...(results.data?.items??[])];if(sort==="rating")copy.sort((a,b)=>(b.rating??-1)-(a.rating??-1));if(sort==="open")copy.sort((a,b)=>Number(b.openNow)-Number(a.openNow));return copy},[results.data,sort]);
  function manual(e:FormEvent){e.preventDefault();if(query.trim().length<2)return;setMessage("");setRadius(5000);setSearchUrl(`/v1/facilities/search?location=${encodeURIComponent(query.trim())}&type=${type}&radius=5000`)}
  function locate(){setMessage("Finding your location…");if(!navigator.geolocation){setMessage("Location is unavailable. Enter your area or city instead.");input.current?.focus();return}navigator.geolocation.getCurrentPosition(pos=>{setMessage("");setRadius(5000);setSearchUrl(`/v1/facilities/nearby?lat=${pos.coords.latitude}&lng=${pos.coords.longitude}&type=${type}&radius=5000`)},error=>{setMessage(error.code===3?"Location timed out. Enter your area or city instead.":"Location access is unavailable. Enter your area or city instead.");input.current?.focus()},{enableHighAccuracy:false,timeout:10000,maximumAge:300000})}
  function repeat(nextRadius:number){setRadius(nextRadius);setSearchUrl(searchUrl.replace(/radius=\d+/,`radius=${nextRadius}`))}
  return <div className="page find-care"><header className="page-header"><div><span className="eyebrow">Find care</span><h1>Hospitals & laboratories</h1><p>Search nearby or enter an area.</p></div><button className="saved-link" onClick={()=>{setSearchUrl("");setMessage("Saved facilities")}}><Heart/> Saved</button></header>
    <section className="care-search"><button className="location-button" onClick={locate}><LocateFixed/><span><strong>Use my location</strong><small>Used only for this search</small></span></button><span className="or">or</span><form onSubmit={manual}><Search/><input ref={input} value={query} onChange={e=>setQuery(e.target.value)} placeholder="City, area, landmark or address" aria-label="Search city, area, landmark or address"/><button aria-label="Search">Search</button></form></section>
    <div className="facility-chips" role="radiogroup" aria-label="Facility type">{types.map(({id,label,icon:Icon})=><button key={id} role="radio" aria-checked={type===id} className={type===id?"active":""} onClick={()=>{setType(id);if(searchUrl)setSearchUrl(searchUrl.replace(/type=[^&]+/,`type=${id}`))}}><Icon/>{label}</button>)}</div>
    {message&&message!=="Saved facilities"&&<div className="location-message"><MapPin/>{message}</div>}
    {searchUrl&&<div className="result-controls"><strong>{results.data?.searchLocation?.label??"Nearby care"}</strong><div><label>Sort <select value={sort} onChange={e=>setSort(e.target.value)}><option value="nearest">Nearest</option><option value="rating">Highest rated</option><option value="open">Open now</option></select></label><span className="view-toggle"><button className={view==="list"?"active":""} onClick={()=>setView("list")} aria-label="List view"><List/></button><button className={view==="map"?"active":""} onClick={()=>setView("map")} aria-label="Map view"><Map/></button></span></div></div>}
    {message==="Saved facilities"?<Saved items={favourites.data?.items??[]} onOpen={setSelected} onRemove={id=>remove.mutate(id)}/>:results.isLoading?<div className="care-loading"><LocateFixed/><strong>{searchUrl.includes("nearby")?"Searching nearby care…":"Searching this area…"}</strong><div className="skeleton-cards"><i/><i/><i/></div></div>:results.error?<div className="care-error"><MapPin/><h2>Search unavailable</h2><p>{(results.error as Error).message}</p><Button variant="secondary" onClick={()=>input.current?.focus()}>Search another location</Button></div>:searchUrl&&items.length===0?<Empty icon={<Building2/>} heading={`No facilities found within ${radius/1000} km`} body="Try a wider area or another location." action={radius<25000?<Button onClick={()=>repeat(radius===5000?10000:25000)}>Expand to {radius===5000?10:25} km</Button>:undefined}/>:view==="map"&&items.length?<CareMap items={items} origin={results.data.searchLocation} onOpen={setSelected}/>:<div className="care-list">{items.map((f:Facility)=><FacilityCard key={f.providerPlaceId} facility={f} saved={saved.has(f.providerPlaceId)} onOpen={()=>setSelected(f)} onSave={()=>saved.has(f.providerPlaceId)?remove.mutate(f.providerPlaceId):save.mutate(f)}/>)}</div>}
    {selected&&<Details facility={selected} saved={saved.has(selected.providerPlaceId)} onClose={()=>setSelected(null)} onSave={()=>saved.has(selected.providerPlaceId)?remove.mutate(selected.providerPlaceId):save.mutate(selected)}/>}<p className="directory-note"><MapPin/> Distance is approximate and does not rank medical quality or suitability.</p>
  </div>
}

function FacilityCard({facility:f,saved,onOpen,onSave}:{facility:Facility;saved:boolean;onOpen:()=>void;onSave:()=>void}){return <article className="care-card"><header><span className={`care-type ${f.category}`}><Building2/></span><div><strong>{f.name}</strong><small>{f.category.replace("_"," ")}</small></div><button className={saved?"heart saved":"heart"} onClick={onSave} aria-label={saved?"Remove saved facility":"Save facility"}><Heart/></button></header><p><MapPin/>{f.address??"Address unavailable"}</p><div className="care-meta"><strong>{distanceLabel(f.distanceMetres)} away</strong>{f.rating!==undefined&&<span><Star/> {f.rating} {f.reviewCount!==undefined&&`(${f.reviewCount})`}</span>}{f.openNow!==undefined&&<Status kind={f.openNow?"green":"grey"} label={f.openNow?"Open":"Closed"}/>}</div><footer><button onClick={onOpen}>View details</button><a href={directions(f)} target="_blank" rel="noreferrer"><Navigation/> Directions</a></footer></article>}
function CareMap({items,origin,onOpen}:{items:Facility[];origin:any;onOpen:(f:Facility)=>void}){const lats=items.map(x=>x.latitude).concat(origin.latitude),lngs=items.map(x=>x.longitude).concat(origin.longitude),minLat=Math.min(...lats),maxLat=Math.max(...lats),minLng=Math.min(...lngs),maxLng=Math.max(...lngs);const pos=(lat:number,lng:number)=>({left:`${8+84*(lng-minLng)/(maxLng-minLng||1)}%`,top:`${8+84*(maxLat-lat)/(maxLat-minLat||1)}%`});return <div className="care-map" role="img" aria-label="Map of nearby facilities"><span className="search-pin" style={pos(origin.latitude,origin.longitude)}><LocateFixed/></span>{items.map((f,i)=><button key={f.providerPlaceId} style={pos(f.latitude,f.longitude)} onClick={()=>onOpen(f)} aria-label={`Open ${f.name}`}><span>{i+1}</span></button>)}<div className="map-legend"><LocateFixed/> Search area <MapPin/> Facilities</div></div>}
function Details({facility:f,saved,onClose,onSave}:{facility:Facility;saved:boolean;onClose:()=>void;onSave:()=>void}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="facility-detail" role="dialog" aria-modal="true"><header><span className="care-type"><Building2/></span><button onClick={onClose} aria-label="Close"><X/></button></header><span className="eyebrow">{f.category.replace("_"," ")}</span><h2>{f.name}</h2><p className="detail-address"><MapPin/>{f.address}</p><div className="care-meta"><strong>{distanceLabel(f.distanceMetres)} away</strong>{f.rating!==undefined&&<span><Star/> {f.rating} ({f.reviewCount??0})</span>}{f.openNow!==undefined&&<Status kind={f.openNow?"green":"grey"} label={f.openNow?"Open":"Closed"}/>}</div>{f.hours?.length&&<div className="hours"><Clock3/><span>{f.hours.map(h=><small key={h}>{h}</small>)}</span></div>}<div className="detail-actions">{f.phone&&<a href={`tel:${f.phone}`}><Phone/> Call</a>}<a href={directions(f)} target="_blank" rel="noreferrer"><Navigation/> Directions</a>{f.website&&<a href={f.website} target="_blank" rel="noreferrer"><ExternalLink/> Website</a>}<button onClick={onSave}><Heart/> {saved?"Remove saved":"Save facility"}</button></div></section></div>}
function Saved({items,onOpen,onRemove}:{items:any[];onOpen:(f:any)=>void;onRemove:(id:string)=>void}){return items.length?<div className="care-list">{items.map(f=><FacilityCard key={f.providerPlaceId} facility={{...f,distanceMetres:0}} saved onOpen={()=>onOpen({...f,distanceMetres:0})} onSave={()=>onRemove(f.providerPlaceId)}/>)}</div>:<Empty icon={<Heart/>} heading="No saved facilities" body="Tap the heart on a hospital, lab or clinic to keep it here."/>}
