import { useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Eye, FilePlus2, FileText, Filter, FlaskConical, Image, Search, UploadCloud } from "lucide-react";
import { Route, Routes, useLocation, useNavigate, useParams } from "react-router-dom";
import { api, send } from "../api";
import { Button, Empty, ErrorState, Field, Loading, Modal, SelectField, Status, fmtDate } from "../components";
import type { Me } from "../App";

function List() {
  const nav=useNavigate(),loc=useLocation(),qc=useQueryClient();
  const [search,setSearch]=useState(""),[category,setCategory]=useState("");
  const [modal,setModal]=useState(new URLSearchParams(loc.search).has("new"));
  const records=useQuery({queryKey:["records",search,category],queryFn:()=>api<any>(`/v1/records?search=${encodeURIComponent(search)}&category=${category}`)});
  const add=useMutation({mutationFn:(body:any)=>send("POST","/v1/records",body),onSuccess:()=>{qc.invalidateQueries({queryKey:["records"]});setModal(false)}});
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();add.mutate(Object.fromEntries(new FormData(e.currentTarget)))}
  return <div className="page"><header className="page-header"><div><span className="eyebrow">Your documents</span><h1>Medical records</h1><p>Reports, images and results in one place.</p></div><Button onClick={()=>setModal(true)}><FilePlus2/> Add record</Button></header><div className="toolbar"><label className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search records" aria-label="Search records"/></label><label className="filter"><Filter/><select value={category} onChange={e=>setCategory(e.target.value)} aria-label="Filter category"><option value="">All</option><option value="laboratory">Laboratory</option><option value="imaging">Imaging</option><option value="prescription">Prescription</option><option value="visit">Visit</option><option value="procedure">Procedure</option><option value="immunization">Immunization</option><option value="other">Other</option></select></label></div>{records.isLoading?<Loading/>:records.error?<ErrorState message={(records.error as Error).message}/>:records.data.items.length===0?<Empty icon={<FileText/>} heading="No records found" body="Add a record or adjust your search." action={<Button onClick={()=>setModal(true)}>Add record</Button>}/>:<div className="cards-list">{records.data.items.map((r:any)=><button className="record-card" key={r.id} onClick={()=>nav(`/records/${r.id}`)}><span className={`category-icon ${r.category}`}><FileText/></span><div><strong>{r.title}</strong><span>{fmtDate(r.reportDate)}</span><small>{r.category} · {r.sourceType.replaceAll("_"," ")}</small></div><Status kind="green" label="Ready"/></button>)}</div>}{modal&&<Modal title="Add medical record" onClose={()=>setModal(false)}><form onSubmit={submit} className="modal-form"><div className="upload-note"><UploadCloud/><div><strong>Create the record first</strong><span>Attach its report image from the record screen.</span></div></div><Field label="Title" name="title" placeholder="e.g. Complete blood count" required/><SelectField label="Category" name="category" required><option value="laboratory">Laboratory</option><option value="imaging">Imaging</option><option value="prescription">Prescription</option><option value="visit">Visit</option><option value="procedure">Procedure</option><option value="immunization">Immunization</option><option value="other">Other</option></SelectField><Field label="Report date" name="reportDate" type="date"/><input type="hidden" name="sourceType" value="manual_entry"/>{add.error&&<p className="form-error">{(add.error as Error).message}</p>}<div className="modal-actions"><Button type="button" variant="secondary" onClick={()=>setModal(false)}>Cancel</Button><Button disabled={add.isPending}>{add.isPending?"Saving…":"Save record"}</Button></div></form></Modal>}</div>
}

function Detail({me:_me}:{me:Me}) {
  const {id}=useParams(),nav=useNavigate(),qc=useQueryClient(); const [uploadError,setUploadError]=useState("");
  const record=useQuery({queryKey:["record",id],queryFn:()=>api<any>(`/v1/records/${id}`)});
  const upload=useMutation({mutationFn:async(file:File)=>{const form=new FormData();form.append("file",file);return api<any>(`/v1/records/${id}/files`,{method:"POST",body:form})},onSuccess:()=>{setUploadError("");qc.invalidateQueries({queryKey:["record",id]})},onError:(e:Error)=>setUploadError(e.message)});
  if(record.isLoading)return <Loading/>;if(record.error)return <ErrorState message={(record.error as Error).message}/>;const r=record.data.record;
  return <div className="page"><button className="back" onClick={()=>nav("/records")}>← Records</button><header className="record-detail-head"><span className={`category-icon ${r.category}`}><FileText/></span><div><span className="eyebrow">{r.category}</span><h1>{r.title}</h1><p>{fmtDate(r.reportDate)} · Version {r.version}</p></div><Status kind="green" label="Ready"/></header><div className="detail-grid"><section className="panel attachments-panel"><header><div><span className="eyebrow">PDF, JPG or PNG</span><h2>Report files</h2></div><label className="upload-button"><UploadCloud/>{upload.isPending?"Uploading…":"Upload"}<input type="file" accept="application/pdf,image/jpeg,image/png" disabled={upload.isPending} onChange={e=>{const file=e.target.files?.[0];if(file)upload.mutate(file);e.currentTarget.value=""}}/></label></header>{uploadError&&<p className="form-error">{uploadError}</p>}{record.data.files?.length?<div className="file-list">{record.data.files.map((f:any)=>{const ready=f.processingStatus==="available";return <article key={f.id}><span className="file-thumb">{f.mime.startsWith("image/")?<Image/>:<FileText/>}</span><div><strong>{f.name}</strong><small>{Math.max(1,Math.round(f.size/1024))} KB</small></div><Status kind={ready?"green":"amber"} label={ready?"Ready":"Checking"}/><button className="eye-button" disabled={!ready} title={ready?"View file":"Waiting for safety checks"} onClick={()=>window.open(`/v1/files/${f.id}/content`,"_blank","noopener,noreferrer")} aria-label={`View ${f.name}`}><Eye/></button></article>})}</div>:<Empty icon={<Image/>} heading="No report image" body="Upload a clear photo, PNG or PDF."/>}</section><section className="panel"><h2>Results</h2>{record.data.observations.length===0?<Empty icon={<FlaskConical/>} heading="No result rows" body="View the report image or add values later."/>:<div className="results-table">{record.data.observations.map((o:any)=><article key={o.id}><div><strong>{o.label}</strong><span>{o.rawValue} {o.unit}</span><small>Range: {o.rawInterval??"Not provided"}</small></div><Status kind={o.evaluation.status} label={o.evaluation.status==="grey"?"Review":o.evaluation.status}/><p>{o.evaluation.wording}</p></article>)}</div>}</section><section className="panel record-facts"><h2>Details</h2><dl><div><dt>Source</dt><dd>{r.sourceType.replaceAll("_"," ")}</dd></div><div><dt>Date</dt><dd>{fmtDate(r.reportDate)}</dd></div><div><dt>Version</dt><dd>{r.version}</dd></div></dl></section></div><p className="clinical-disclaimer">Netrue does not diagnose or calculate a health score. Discuss results with a healthcare professional.</p></div>
}

export default function Records({me}:{me:Me}){return <Routes><Route index element={<List/>}/><Route path=":id" element={<Detail me={me}/>}/></Routes>}
